fail_fast: false
repos:
  - repo: local
    hooks:
      - id: clang-format
        name: Run Clang Format
        entry: clang_restage
        language: script
        files: \.(c|cpp|h|hpp)$
        stages: [pre-commit]