/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockstm32f4xx_hal.h"

static const char* CMockString_Delay = "Delay";
static const char* CMockString_Freq = "Freq";
static const char* CMockString_HAL_DBGMCU_DisableDBGSleepMode = "HAL_DBGMCU_DisableDBGSleepMode";
static const char* CMockString_HAL_DBGMCU_DisableDBGStandbyMode = "HAL_DBGMCU_DisableDBGStandbyMode";
static const char* CMockString_HAL_DBGMCU_DisableDBGStopMode = "HAL_DBGMCU_DisableDBGStopMode";
static const char* CMockString_HAL_DBGMCU_EnableDBGSleepMode = "HAL_DBGMCU_EnableDBGSleepMode";
static const char* CMockString_HAL_DBGMCU_EnableDBGStandbyMode = "HAL_DBGMCU_EnableDBGStandbyMode";
static const char* CMockString_HAL_DBGMCU_EnableDBGStopMode = "HAL_DBGMCU_EnableDBGStopMode";
static const char* CMockString_HAL_DeInit = "HAL_DeInit";
static const char* CMockString_HAL_Delay = "HAL_Delay";
static const char* CMockString_HAL_DisableCompensationCell = "HAL_DisableCompensationCell";
static const char* CMockString_HAL_DisableMemorySwappingBank = "HAL_DisableMemorySwappingBank";
static const char* CMockString_HAL_EnableCompensationCell = "HAL_EnableCompensationCell";
static const char* CMockString_HAL_EnableMemorySwappingBank = "HAL_EnableMemorySwappingBank";
static const char* CMockString_HAL_GetDEVID = "HAL_GetDEVID";
static const char* CMockString_HAL_GetHalVersion = "HAL_GetHalVersion";
static const char* CMockString_HAL_GetREVID = "HAL_GetREVID";
static const char* CMockString_HAL_GetTick = "HAL_GetTick";
static const char* CMockString_HAL_GetTickFreq = "HAL_GetTickFreq";
static const char* CMockString_HAL_GetTickPrio = "HAL_GetTickPrio";
static const char* CMockString_HAL_GetUIDw0 = "HAL_GetUIDw0";
static const char* CMockString_HAL_GetUIDw1 = "HAL_GetUIDw1";
static const char* CMockString_HAL_GetUIDw2 = "HAL_GetUIDw2";
static const char* CMockString_HAL_IncTick = "HAL_IncTick";
static const char* CMockString_HAL_Init = "HAL_Init";
static const char* CMockString_HAL_InitTick = "HAL_InitTick";
static const char* CMockString_HAL_MspDeInit = "HAL_MspDeInit";
static const char* CMockString_HAL_MspInit = "HAL_MspInit";
static const char* CMockString_HAL_ResumeTick = "HAL_ResumeTick";
static const char* CMockString_HAL_SetTickFreq = "HAL_SetTickFreq";
static const char* CMockString_HAL_SuspendTick = "HAL_SuspendTick";
static const char* CMockString_TickPriority = "TickPriority";

typedef struct _CMOCK_HAL_Init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;

} CMOCK_HAL_Init_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DeInit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;

} CMOCK_HAL_DeInit_CALL_INSTANCE;

typedef struct _CMOCK_HAL_MspInit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_HAL_MspInit_CALL_INSTANCE;

typedef struct _CMOCK_HAL_MspDeInit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_HAL_MspDeInit_CALL_INSTANCE;

typedef struct _CMOCK_HAL_InitTick_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  uint32_t Expected_TickPriority;

} CMOCK_HAL_InitTick_CALL_INSTANCE;

typedef struct _CMOCK_HAL_IncTick_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_HAL_IncTick_CALL_INSTANCE;

typedef struct _CMOCK_HAL_Delay_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t Expected_Delay;

} CMOCK_HAL_Delay_CALL_INSTANCE;

typedef struct _CMOCK_HAL_GetTick_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t ReturnVal;

} CMOCK_HAL_GetTick_CALL_INSTANCE;

typedef struct _CMOCK_HAL_GetTickPrio_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t ReturnVal;

} CMOCK_HAL_GetTickPrio_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SetTickFreq_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  HAL_TickFreqTypeDef Expected_Freq;

} CMOCK_HAL_SetTickFreq_CALL_INSTANCE;

typedef struct _CMOCK_HAL_GetTickFreq_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_TickFreqTypeDef ReturnVal;

} CMOCK_HAL_GetTickFreq_CALL_INSTANCE;

typedef struct _CMOCK_HAL_SuspendTick_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_HAL_SuspendTick_CALL_INSTANCE;

typedef struct _CMOCK_HAL_ResumeTick_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_HAL_ResumeTick_CALL_INSTANCE;

typedef struct _CMOCK_HAL_GetHalVersion_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t ReturnVal;

} CMOCK_HAL_GetHalVersion_CALL_INSTANCE;

typedef struct _CMOCK_HAL_GetREVID_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t ReturnVal;

} CMOCK_HAL_GetREVID_CALL_INSTANCE;

typedef struct _CMOCK_HAL_GetDEVID_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t ReturnVal;

} CMOCK_HAL_GetDEVID_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DBGMCU_EnableDBGSleepMode_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_HAL_DBGMCU_EnableDBGSleepMode_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DBGMCU_DisableDBGSleepMode_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_HAL_DBGMCU_DisableDBGSleepMode_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DBGMCU_EnableDBGStopMode_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_HAL_DBGMCU_EnableDBGStopMode_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DBGMCU_DisableDBGStopMode_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_HAL_DBGMCU_DisableDBGStopMode_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DBGMCU_EnableDBGStandbyMode_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_HAL_DBGMCU_EnableDBGStandbyMode_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DBGMCU_DisableDBGStandbyMode_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_HAL_DBGMCU_DisableDBGStandbyMode_CALL_INSTANCE;

typedef struct _CMOCK_HAL_EnableCompensationCell_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_HAL_EnableCompensationCell_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DisableCompensationCell_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_HAL_DisableCompensationCell_CALL_INSTANCE;

typedef struct _CMOCK_HAL_GetUIDw0_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t ReturnVal;

} CMOCK_HAL_GetUIDw0_CALL_INSTANCE;

typedef struct _CMOCK_HAL_GetUIDw1_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t ReturnVal;

} CMOCK_HAL_GetUIDw1_CALL_INSTANCE;

typedef struct _CMOCK_HAL_GetUIDw2_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t ReturnVal;

} CMOCK_HAL_GetUIDw2_CALL_INSTANCE;

typedef struct _CMOCK_HAL_EnableMemorySwappingBank_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_HAL_EnableMemorySwappingBank_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DisableMemorySwappingBank_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_HAL_DisableMemorySwappingBank_CALL_INSTANCE;

static struct Mockstm32f4xx_halInstance
{
  CMOCK_MEM_INDEX_TYPE HAL_Init_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DeInit_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_MspInit_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_MspDeInit_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_InitTick_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_IncTick_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_Delay_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_GetTick_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_GetTickPrio_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_SetTickFreq_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_GetTickFreq_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_SuspendTick_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_ResumeTick_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_GetHalVersion_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_GetREVID_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_GetDEVID_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DBGMCU_EnableDBGSleepMode_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DBGMCU_DisableDBGSleepMode_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DBGMCU_EnableDBGStopMode_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DBGMCU_DisableDBGStopMode_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DBGMCU_EnableDBGStandbyMode_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DBGMCU_DisableDBGStandbyMode_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_EnableCompensationCell_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DisableCompensationCell_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_GetUIDw0_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_GetUIDw1_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_GetUIDw2_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_EnableMemorySwappingBank_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DisableMemorySwappingBank_CallInstance;
} Mock;


void Mockstm32f4xx_hal_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.HAL_Init_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_Init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DeInit_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DeInit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_MspInit_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_MspInit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_MspDeInit_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_MspDeInit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_InitTick_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_InitTick);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_IncTick_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_IncTick);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_Delay_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_Delay);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_GetTick_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_GetTick);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_GetTickPrio_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_GetTickPrio);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_SetTickFreq_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_SetTickFreq);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_GetTickFreq_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_GetTickFreq);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_SuspendTick_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_SuspendTick);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_ResumeTick_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_ResumeTick);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_GetHalVersion_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_GetHalVersion);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_GetREVID_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_GetREVID);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_GetDEVID_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_GetDEVID);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DBGMCU_EnableDBGSleepMode_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DBGMCU_EnableDBGSleepMode);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DBGMCU_DisableDBGSleepMode_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DBGMCU_DisableDBGSleepMode);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DBGMCU_EnableDBGStopMode_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DBGMCU_EnableDBGStopMode);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DBGMCU_DisableDBGStopMode_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DBGMCU_DisableDBGStopMode);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DBGMCU_EnableDBGStandbyMode_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DBGMCU_EnableDBGStandbyMode);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DBGMCU_DisableDBGStandbyMode_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DBGMCU_DisableDBGStandbyMode);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_EnableCompensationCell_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_EnableCompensationCell);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DisableCompensationCell_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DisableCompensationCell);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_GetUIDw0_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_GetUIDw0);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_GetUIDw1_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_GetUIDw1);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_GetUIDw2_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_GetUIDw2);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_EnableMemorySwappingBank_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_EnableMemorySwappingBank);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DisableMemorySwappingBank_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DisableMemorySwappingBank);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockstm32f4xx_hal_Init(void)
{
  Mockstm32f4xx_hal_Destroy();
}

void Mockstm32f4xx_hal_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

HAL_StatusTypeDef HAL_Init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_Init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_Init);
  cmock_call_instance = (CMOCK_HAL_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_Init_CallInstance);
  Mock.HAL_Init_CallInstance = CMock_Guts_MemNext(Mock.HAL_Init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void HAL_Init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_Init_CALL_INSTANCE));
  CMOCK_HAL_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_Init_CallInstance = CMock_Guts_MemChain(Mock.HAL_Init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_DeInit(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DeInit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DeInit);
  cmock_call_instance = (CMOCK_HAL_DeInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DeInit_CallInstance);
  Mock.HAL_DeInit_CallInstance = CMock_Guts_MemNext(Mock.HAL_DeInit_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void HAL_DeInit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DeInit_CALL_INSTANCE));
  CMOCK_HAL_DeInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DeInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DeInit_CallInstance = CMock_Guts_MemChain(Mock.HAL_DeInit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

void HAL_MspInit(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_MspInit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_MspInit);
  cmock_call_instance = (CMOCK_HAL_MspInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_MspInit_CallInstance);
  Mock.HAL_MspInit_CallInstance = CMock_Guts_MemNext(Mock.HAL_MspInit_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void HAL_MspInit_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_MspInit_CALL_INSTANCE));
  CMOCK_HAL_MspInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_MspInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_MspInit_CallInstance = CMock_Guts_MemChain(Mock.HAL_MspInit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void HAL_MspDeInit(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_MspDeInit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_MspDeInit);
  cmock_call_instance = (CMOCK_HAL_MspDeInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_MspDeInit_CallInstance);
  Mock.HAL_MspDeInit_CallInstance = CMock_Guts_MemNext(Mock.HAL_MspDeInit_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void HAL_MspDeInit_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_MspDeInit_CALL_INSTANCE));
  CMOCK_HAL_MspDeInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_MspDeInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_MspDeInit_CallInstance = CMock_Guts_MemChain(Mock.HAL_MspDeInit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

HAL_StatusTypeDef HAL_InitTick(uint32_t TickPriority)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_InitTick_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_InitTick);
  cmock_call_instance = (CMOCK_HAL_InitTick_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_InitTick_CallInstance);
  Mock.HAL_InitTick_CallInstance = CMock_Guts_MemNext(Mock.HAL_InitTick_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_InitTick,CMockString_TickPriority);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_TickPriority, TickPriority, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_InitTick(CMOCK_HAL_InitTick_CALL_INSTANCE* cmock_call_instance, uint32_t TickPriority);
void CMockExpectParameters_HAL_InitTick(CMOCK_HAL_InitTick_CALL_INSTANCE* cmock_call_instance, uint32_t TickPriority)
{
  cmock_call_instance->Expected_TickPriority = TickPriority;
}

void HAL_InitTick_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t TickPriority, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_InitTick_CALL_INSTANCE));
  CMOCK_HAL_InitTick_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_InitTick_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_InitTick_CallInstance = CMock_Guts_MemChain(Mock.HAL_InitTick_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_InitTick(cmock_call_instance, TickPriority);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

void HAL_IncTick(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_IncTick_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_IncTick);
  cmock_call_instance = (CMOCK_HAL_IncTick_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_IncTick_CallInstance);
  Mock.HAL_IncTick_CallInstance = CMock_Guts_MemNext(Mock.HAL_IncTick_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void HAL_IncTick_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_IncTick_CALL_INSTANCE));
  CMOCK_HAL_IncTick_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_IncTick_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_IncTick_CallInstance = CMock_Guts_MemChain(Mock.HAL_IncTick_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void HAL_Delay(uint32_t Delay)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_Delay_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_Delay);
  cmock_call_instance = (CMOCK_HAL_Delay_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_Delay_CallInstance);
  Mock.HAL_Delay_CallInstance = CMock_Guts_MemNext(Mock.HAL_Delay_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_Delay,CMockString_Delay);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_Delay, Delay, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_Delay(CMOCK_HAL_Delay_CALL_INSTANCE* cmock_call_instance, uint32_t Delay);
void CMockExpectParameters_HAL_Delay(CMOCK_HAL_Delay_CALL_INSTANCE* cmock_call_instance, uint32_t Delay)
{
  cmock_call_instance->Expected_Delay = Delay;
}

void HAL_Delay_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t Delay)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_Delay_CALL_INSTANCE));
  CMOCK_HAL_Delay_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_Delay_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_Delay_CallInstance = CMock_Guts_MemChain(Mock.HAL_Delay_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_Delay(cmock_call_instance, Delay);
}

uint32_t HAL_GetTick(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_GetTick_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_GetTick);
  cmock_call_instance = (CMOCK_HAL_GetTick_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_GetTick_CallInstance);
  Mock.HAL_GetTick_CallInstance = CMock_Guts_MemNext(Mock.HAL_GetTick_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void HAL_GetTick_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_GetTick_CALL_INSTANCE));
  CMOCK_HAL_GetTick_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_GetTick_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_GetTick_CallInstance = CMock_Guts_MemChain(Mock.HAL_GetTick_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

uint32_t HAL_GetTickPrio(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_GetTickPrio_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_GetTickPrio);
  cmock_call_instance = (CMOCK_HAL_GetTickPrio_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_GetTickPrio_CallInstance);
  Mock.HAL_GetTickPrio_CallInstance = CMock_Guts_MemNext(Mock.HAL_GetTickPrio_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void HAL_GetTickPrio_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_GetTickPrio_CALL_INSTANCE));
  CMOCK_HAL_GetTickPrio_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_GetTickPrio_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_GetTickPrio_CallInstance = CMock_Guts_MemChain(Mock.HAL_GetTickPrio_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

HAL_StatusTypeDef HAL_SetTickFreq(HAL_TickFreqTypeDef Freq)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_SetTickFreq_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_SetTickFreq);
  cmock_call_instance = (CMOCK_HAL_SetTickFreq_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SetTickFreq_CallInstance);
  Mock.HAL_SetTickFreq_CallInstance = CMock_Guts_MemNext(Mock.HAL_SetTickFreq_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_SetTickFreq,CMockString_Freq);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_Freq), (void*)(&Freq), sizeof(HAL_TickFreqTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_SetTickFreq(CMOCK_HAL_SetTickFreq_CALL_INSTANCE* cmock_call_instance, HAL_TickFreqTypeDef Freq);
void CMockExpectParameters_HAL_SetTickFreq(CMOCK_HAL_SetTickFreq_CALL_INSTANCE* cmock_call_instance, HAL_TickFreqTypeDef Freq)
{
  memcpy((void*)(&cmock_call_instance->Expected_Freq), (void*)(&Freq),
         sizeof(HAL_TickFreqTypeDef[sizeof(Freq) == sizeof(HAL_TickFreqTypeDef) ? 1 : -1])); /* add HAL_TickFreqTypeDef to :treat_as_array if this causes an error */
}

void HAL_SetTickFreq_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, HAL_TickFreqTypeDef Freq, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SetTickFreq_CALL_INSTANCE));
  CMOCK_HAL_SetTickFreq_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SetTickFreq_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_SetTickFreq_CallInstance = CMock_Guts_MemChain(Mock.HAL_SetTickFreq_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_SetTickFreq(cmock_call_instance, Freq);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_TickFreqTypeDef HAL_GetTickFreq(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_GetTickFreq_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_GetTickFreq);
  cmock_call_instance = (CMOCK_HAL_GetTickFreq_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_GetTickFreq_CallInstance);
  Mock.HAL_GetTickFreq_CallInstance = CMock_Guts_MemNext(Mock.HAL_GetTickFreq_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void HAL_GetTickFreq_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, HAL_TickFreqTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_GetTickFreq_CALL_INSTANCE));
  CMOCK_HAL_GetTickFreq_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_GetTickFreq_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_GetTickFreq_CallInstance = CMock_Guts_MemChain(Mock.HAL_GetTickFreq_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_TickFreqTypeDef[sizeof(cmock_to_return) == sizeof(HAL_TickFreqTypeDef) ? 1 : -1])); /* add HAL_TickFreqTypeDef to :treat_as_array if this causes an error */
}

void HAL_SuspendTick(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_SuspendTick_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_SuspendTick);
  cmock_call_instance = (CMOCK_HAL_SuspendTick_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_SuspendTick_CallInstance);
  Mock.HAL_SuspendTick_CallInstance = CMock_Guts_MemNext(Mock.HAL_SuspendTick_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void HAL_SuspendTick_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_SuspendTick_CALL_INSTANCE));
  CMOCK_HAL_SuspendTick_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_SuspendTick_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_SuspendTick_CallInstance = CMock_Guts_MemChain(Mock.HAL_SuspendTick_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void HAL_ResumeTick(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_ResumeTick_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_ResumeTick);
  cmock_call_instance = (CMOCK_HAL_ResumeTick_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_ResumeTick_CallInstance);
  Mock.HAL_ResumeTick_CallInstance = CMock_Guts_MemNext(Mock.HAL_ResumeTick_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void HAL_ResumeTick_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_ResumeTick_CALL_INSTANCE));
  CMOCK_HAL_ResumeTick_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_ResumeTick_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_ResumeTick_CallInstance = CMock_Guts_MemChain(Mock.HAL_ResumeTick_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

uint32_t HAL_GetHalVersion(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_GetHalVersion_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_GetHalVersion);
  cmock_call_instance = (CMOCK_HAL_GetHalVersion_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_GetHalVersion_CallInstance);
  Mock.HAL_GetHalVersion_CallInstance = CMock_Guts_MemNext(Mock.HAL_GetHalVersion_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void HAL_GetHalVersion_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_GetHalVersion_CALL_INSTANCE));
  CMOCK_HAL_GetHalVersion_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_GetHalVersion_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_GetHalVersion_CallInstance = CMock_Guts_MemChain(Mock.HAL_GetHalVersion_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

uint32_t HAL_GetREVID(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_GetREVID_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_GetREVID);
  cmock_call_instance = (CMOCK_HAL_GetREVID_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_GetREVID_CallInstance);
  Mock.HAL_GetREVID_CallInstance = CMock_Guts_MemNext(Mock.HAL_GetREVID_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void HAL_GetREVID_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_GetREVID_CALL_INSTANCE));
  CMOCK_HAL_GetREVID_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_GetREVID_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_GetREVID_CallInstance = CMock_Guts_MemChain(Mock.HAL_GetREVID_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

uint32_t HAL_GetDEVID(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_GetDEVID_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_GetDEVID);
  cmock_call_instance = (CMOCK_HAL_GetDEVID_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_GetDEVID_CallInstance);
  Mock.HAL_GetDEVID_CallInstance = CMock_Guts_MemNext(Mock.HAL_GetDEVID_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void HAL_GetDEVID_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_GetDEVID_CALL_INSTANCE));
  CMOCK_HAL_GetDEVID_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_GetDEVID_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_GetDEVID_CallInstance = CMock_Guts_MemChain(Mock.HAL_GetDEVID_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void HAL_DBGMCU_EnableDBGSleepMode(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DBGMCU_EnableDBGSleepMode_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DBGMCU_EnableDBGSleepMode);
  cmock_call_instance = (CMOCK_HAL_DBGMCU_EnableDBGSleepMode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DBGMCU_EnableDBGSleepMode_CallInstance);
  Mock.HAL_DBGMCU_EnableDBGSleepMode_CallInstance = CMock_Guts_MemNext(Mock.HAL_DBGMCU_EnableDBGSleepMode_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void HAL_DBGMCU_EnableDBGSleepMode_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DBGMCU_EnableDBGSleepMode_CALL_INSTANCE));
  CMOCK_HAL_DBGMCU_EnableDBGSleepMode_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DBGMCU_EnableDBGSleepMode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DBGMCU_EnableDBGSleepMode_CallInstance = CMock_Guts_MemChain(Mock.HAL_DBGMCU_EnableDBGSleepMode_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void HAL_DBGMCU_DisableDBGSleepMode(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DBGMCU_DisableDBGSleepMode_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DBGMCU_DisableDBGSleepMode);
  cmock_call_instance = (CMOCK_HAL_DBGMCU_DisableDBGSleepMode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DBGMCU_DisableDBGSleepMode_CallInstance);
  Mock.HAL_DBGMCU_DisableDBGSleepMode_CallInstance = CMock_Guts_MemNext(Mock.HAL_DBGMCU_DisableDBGSleepMode_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void HAL_DBGMCU_DisableDBGSleepMode_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DBGMCU_DisableDBGSleepMode_CALL_INSTANCE));
  CMOCK_HAL_DBGMCU_DisableDBGSleepMode_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DBGMCU_DisableDBGSleepMode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DBGMCU_DisableDBGSleepMode_CallInstance = CMock_Guts_MemChain(Mock.HAL_DBGMCU_DisableDBGSleepMode_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void HAL_DBGMCU_EnableDBGStopMode(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DBGMCU_EnableDBGStopMode_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DBGMCU_EnableDBGStopMode);
  cmock_call_instance = (CMOCK_HAL_DBGMCU_EnableDBGStopMode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DBGMCU_EnableDBGStopMode_CallInstance);
  Mock.HAL_DBGMCU_EnableDBGStopMode_CallInstance = CMock_Guts_MemNext(Mock.HAL_DBGMCU_EnableDBGStopMode_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void HAL_DBGMCU_EnableDBGStopMode_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DBGMCU_EnableDBGStopMode_CALL_INSTANCE));
  CMOCK_HAL_DBGMCU_EnableDBGStopMode_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DBGMCU_EnableDBGStopMode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DBGMCU_EnableDBGStopMode_CallInstance = CMock_Guts_MemChain(Mock.HAL_DBGMCU_EnableDBGStopMode_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void HAL_DBGMCU_DisableDBGStopMode(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DBGMCU_DisableDBGStopMode_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DBGMCU_DisableDBGStopMode);
  cmock_call_instance = (CMOCK_HAL_DBGMCU_DisableDBGStopMode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DBGMCU_DisableDBGStopMode_CallInstance);
  Mock.HAL_DBGMCU_DisableDBGStopMode_CallInstance = CMock_Guts_MemNext(Mock.HAL_DBGMCU_DisableDBGStopMode_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void HAL_DBGMCU_DisableDBGStopMode_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DBGMCU_DisableDBGStopMode_CALL_INSTANCE));
  CMOCK_HAL_DBGMCU_DisableDBGStopMode_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DBGMCU_DisableDBGStopMode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DBGMCU_DisableDBGStopMode_CallInstance = CMock_Guts_MemChain(Mock.HAL_DBGMCU_DisableDBGStopMode_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void HAL_DBGMCU_EnableDBGStandbyMode(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DBGMCU_EnableDBGStandbyMode_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DBGMCU_EnableDBGStandbyMode);
  cmock_call_instance = (CMOCK_HAL_DBGMCU_EnableDBGStandbyMode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DBGMCU_EnableDBGStandbyMode_CallInstance);
  Mock.HAL_DBGMCU_EnableDBGStandbyMode_CallInstance = CMock_Guts_MemNext(Mock.HAL_DBGMCU_EnableDBGStandbyMode_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void HAL_DBGMCU_EnableDBGStandbyMode_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DBGMCU_EnableDBGStandbyMode_CALL_INSTANCE));
  CMOCK_HAL_DBGMCU_EnableDBGStandbyMode_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DBGMCU_EnableDBGStandbyMode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DBGMCU_EnableDBGStandbyMode_CallInstance = CMock_Guts_MemChain(Mock.HAL_DBGMCU_EnableDBGStandbyMode_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void HAL_DBGMCU_DisableDBGStandbyMode(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DBGMCU_DisableDBGStandbyMode_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DBGMCU_DisableDBGStandbyMode);
  cmock_call_instance = (CMOCK_HAL_DBGMCU_DisableDBGStandbyMode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DBGMCU_DisableDBGStandbyMode_CallInstance);
  Mock.HAL_DBGMCU_DisableDBGStandbyMode_CallInstance = CMock_Guts_MemNext(Mock.HAL_DBGMCU_DisableDBGStandbyMode_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void HAL_DBGMCU_DisableDBGStandbyMode_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DBGMCU_DisableDBGStandbyMode_CALL_INSTANCE));
  CMOCK_HAL_DBGMCU_DisableDBGStandbyMode_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DBGMCU_DisableDBGStandbyMode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DBGMCU_DisableDBGStandbyMode_CallInstance = CMock_Guts_MemChain(Mock.HAL_DBGMCU_DisableDBGStandbyMode_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void HAL_EnableCompensationCell(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_EnableCompensationCell_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_EnableCompensationCell);
  cmock_call_instance = (CMOCK_HAL_EnableCompensationCell_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_EnableCompensationCell_CallInstance);
  Mock.HAL_EnableCompensationCell_CallInstance = CMock_Guts_MemNext(Mock.HAL_EnableCompensationCell_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void HAL_EnableCompensationCell_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_EnableCompensationCell_CALL_INSTANCE));
  CMOCK_HAL_EnableCompensationCell_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_EnableCompensationCell_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_EnableCompensationCell_CallInstance = CMock_Guts_MemChain(Mock.HAL_EnableCompensationCell_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void HAL_DisableCompensationCell(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DisableCompensationCell_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DisableCompensationCell);
  cmock_call_instance = (CMOCK_HAL_DisableCompensationCell_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DisableCompensationCell_CallInstance);
  Mock.HAL_DisableCompensationCell_CallInstance = CMock_Guts_MemNext(Mock.HAL_DisableCompensationCell_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void HAL_DisableCompensationCell_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DisableCompensationCell_CALL_INSTANCE));
  CMOCK_HAL_DisableCompensationCell_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DisableCompensationCell_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DisableCompensationCell_CallInstance = CMock_Guts_MemChain(Mock.HAL_DisableCompensationCell_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

uint32_t HAL_GetUIDw0(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_GetUIDw0_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_GetUIDw0);
  cmock_call_instance = (CMOCK_HAL_GetUIDw0_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_GetUIDw0_CallInstance);
  Mock.HAL_GetUIDw0_CallInstance = CMock_Guts_MemNext(Mock.HAL_GetUIDw0_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void HAL_GetUIDw0_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_GetUIDw0_CALL_INSTANCE));
  CMOCK_HAL_GetUIDw0_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_GetUIDw0_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_GetUIDw0_CallInstance = CMock_Guts_MemChain(Mock.HAL_GetUIDw0_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

uint32_t HAL_GetUIDw1(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_GetUIDw1_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_GetUIDw1);
  cmock_call_instance = (CMOCK_HAL_GetUIDw1_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_GetUIDw1_CallInstance);
  Mock.HAL_GetUIDw1_CallInstance = CMock_Guts_MemNext(Mock.HAL_GetUIDw1_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void HAL_GetUIDw1_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_GetUIDw1_CALL_INSTANCE));
  CMOCK_HAL_GetUIDw1_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_GetUIDw1_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_GetUIDw1_CallInstance = CMock_Guts_MemChain(Mock.HAL_GetUIDw1_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

uint32_t HAL_GetUIDw2(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_GetUIDw2_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_GetUIDw2);
  cmock_call_instance = (CMOCK_HAL_GetUIDw2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_GetUIDw2_CallInstance);
  Mock.HAL_GetUIDw2_CallInstance = CMock_Guts_MemNext(Mock.HAL_GetUIDw2_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void HAL_GetUIDw2_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_GetUIDw2_CALL_INSTANCE));
  CMOCK_HAL_GetUIDw2_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_GetUIDw2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_GetUIDw2_CallInstance = CMock_Guts_MemChain(Mock.HAL_GetUIDw2_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void HAL_EnableMemorySwappingBank(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_EnableMemorySwappingBank_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_EnableMemorySwappingBank);
  cmock_call_instance = (CMOCK_HAL_EnableMemorySwappingBank_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_EnableMemorySwappingBank_CallInstance);
  Mock.HAL_EnableMemorySwappingBank_CallInstance = CMock_Guts_MemNext(Mock.HAL_EnableMemorySwappingBank_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void HAL_EnableMemorySwappingBank_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_EnableMemorySwappingBank_CALL_INSTANCE));
  CMOCK_HAL_EnableMemorySwappingBank_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_EnableMemorySwappingBank_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_EnableMemorySwappingBank_CallInstance = CMock_Guts_MemChain(Mock.HAL_EnableMemorySwappingBank_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void HAL_DisableMemorySwappingBank(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DisableMemorySwappingBank_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DisableMemorySwappingBank);
  cmock_call_instance = (CMOCK_HAL_DisableMemorySwappingBank_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DisableMemorySwappingBank_CallInstance);
  Mock.HAL_DisableMemorySwappingBank_CallInstance = CMock_Guts_MemNext(Mock.HAL_DisableMemorySwappingBank_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void HAL_DisableMemorySwappingBank_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DisableMemorySwappingBank_CALL_INSTANCE));
  CMOCK_HAL_DisableMemorySwappingBank_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DisableMemorySwappingBank_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DisableMemorySwappingBank_CallInstance = CMock_Guts_MemChain(Mock.HAL_DisableMemorySwappingBank_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

