/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockcan.h"

static const char* CMockString_can = "can";
static const char* CMockString_can_add_filter_extended = "can_add_filter_extended";
static const char* CMockString_can_add_filter_standard = "can_add_filter_standard";
static const char* CMockString_can_id_list = "can_id_list";
static const char* CMockString_can_init = "can_init";
static const char* CMockString_can_send_msg = "can_send_msg";
static const char* CMockString_msg = "msg";

typedef struct _CMOCK_can_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  can_t* Expected_can;

} CMOCK_can_init_CALL_INSTANCE;

typedef struct _CMOCK_can_add_filter_standard_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  can_t* Expected_can;
  uint16_t* Expected_can_id_list;

} CMOCK_can_add_filter_standard_CALL_INSTANCE;

typedef struct _CMOCK_can_add_filter_extended_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  can_t* Expected_can;
  uint32_t* Expected_can_id_list;

} CMOCK_can_add_filter_extended_CALL_INSTANCE;

typedef struct _CMOCK_can_send_msg_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  can_t* Expected_can;
  can_msg_t* Expected_msg;

} CMOCK_can_send_msg_CALL_INSTANCE;

static struct MockcanInstance
{
  CMOCK_MEM_INDEX_TYPE can_init_CallInstance;
  CMOCK_MEM_INDEX_TYPE can_add_filter_standard_CallInstance;
  CMOCK_MEM_INDEX_TYPE can_add_filter_extended_CallInstance;
  CMOCK_MEM_INDEX_TYPE can_send_msg_CallInstance;
} Mock;


void Mockcan_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.can_init_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_can_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.can_add_filter_standard_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_can_add_filter_standard);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.can_add_filter_extended_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_can_add_filter_extended);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.can_send_msg_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_can_send_msg);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockcan_Init(void)
{
  Mockcan_Destroy();
}

void Mockcan_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

HAL_StatusTypeDef can_init(can_t* can)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_can_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_can_init);
  cmock_call_instance = (CMOCK_can_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.can_init_CallInstance);
  Mock.can_init_CallInstance = CMock_Guts_MemNext(Mock.can_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_can_init,CMockString_can);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_can), (void*)(can), sizeof(can_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_can_init(CMOCK_can_init_CALL_INSTANCE* cmock_call_instance, can_t* can);
void CMockExpectParameters_can_init(CMOCK_can_init_CALL_INSTANCE* cmock_call_instance, can_t* can)
{
  cmock_call_instance->Expected_can = can;
}

void can_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, can_t* can, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_can_init_CALL_INSTANCE));
  CMOCK_can_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_can_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.can_init_CallInstance = CMock_Guts_MemChain(Mock.can_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_can_init(cmock_call_instance, can);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef can_add_filter_standard(can_t* can, uint16_t* can_id_list)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_can_add_filter_standard_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_can_add_filter_standard);
  cmock_call_instance = (CMOCK_can_add_filter_standard_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.can_add_filter_standard_CallInstance);
  Mock.can_add_filter_standard_CallInstance = CMock_Guts_MemNext(Mock.can_add_filter_standard_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_can_add_filter_standard,CMockString_can);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_can), (void*)(can), sizeof(can_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_can_add_filter_standard,CMockString_can_id_list);
    if (cmock_call_instance->Expected_can_id_list == NULL)
      { UNITY_TEST_ASSERT_NULL(can_id_list, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX16_ARRAY(cmock_call_instance->Expected_can_id_list, can_id_list, 1, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_can_add_filter_standard(CMOCK_can_add_filter_standard_CALL_INSTANCE* cmock_call_instance, can_t* can, uint16_t* can_id_list);
void CMockExpectParameters_can_add_filter_standard(CMOCK_can_add_filter_standard_CALL_INSTANCE* cmock_call_instance, can_t* can, uint16_t* can_id_list)
{
  cmock_call_instance->Expected_can = can;
  cmock_call_instance->Expected_can_id_list = can_id_list;
}

void can_add_filter_standard_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, can_t* can, uint16_t* can_id_list, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_can_add_filter_standard_CALL_INSTANCE));
  CMOCK_can_add_filter_standard_CALL_INSTANCE* cmock_call_instance = (CMOCK_can_add_filter_standard_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.can_add_filter_standard_CallInstance = CMock_Guts_MemChain(Mock.can_add_filter_standard_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_can_add_filter_standard(cmock_call_instance, can, can_id_list);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef can_add_filter_extended(can_t* can, uint32_t* can_id_list)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_can_add_filter_extended_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_can_add_filter_extended);
  cmock_call_instance = (CMOCK_can_add_filter_extended_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.can_add_filter_extended_CallInstance);
  Mock.can_add_filter_extended_CallInstance = CMock_Guts_MemNext(Mock.can_add_filter_extended_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_can_add_filter_extended,CMockString_can);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_can), (void*)(can), sizeof(can_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_can_add_filter_extended,CMockString_can_id_list);
    if (cmock_call_instance->Expected_can_id_list == NULL)
      { UNITY_TEST_ASSERT_NULL(can_id_list, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_can_id_list, can_id_list, 1, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_can_add_filter_extended(CMOCK_can_add_filter_extended_CALL_INSTANCE* cmock_call_instance, can_t* can, uint32_t* can_id_list);
void CMockExpectParameters_can_add_filter_extended(CMOCK_can_add_filter_extended_CALL_INSTANCE* cmock_call_instance, can_t* can, uint32_t* can_id_list)
{
  cmock_call_instance->Expected_can = can;
  cmock_call_instance->Expected_can_id_list = can_id_list;
}

void can_add_filter_extended_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, can_t* can, uint32_t* can_id_list, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_can_add_filter_extended_CALL_INSTANCE));
  CMOCK_can_add_filter_extended_CALL_INSTANCE* cmock_call_instance = (CMOCK_can_add_filter_extended_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.can_add_filter_extended_CallInstance = CMock_Guts_MemChain(Mock.can_add_filter_extended_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_can_add_filter_extended(cmock_call_instance, can, can_id_list);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef can_send_msg(can_t* can, can_msg_t* msg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_can_send_msg_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_can_send_msg);
  cmock_call_instance = (CMOCK_can_send_msg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.can_send_msg_CallInstance);
  Mock.can_send_msg_CallInstance = CMock_Guts_MemNext(Mock.can_send_msg_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_can_send_msg,CMockString_can);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_can), (void*)(can), sizeof(can_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_can_send_msg,CMockString_msg);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_msg), (void*)(msg), sizeof(can_msg_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_can_send_msg(CMOCK_can_send_msg_CALL_INSTANCE* cmock_call_instance, can_t* can, can_msg_t* msg);
void CMockExpectParameters_can_send_msg(CMOCK_can_send_msg_CALL_INSTANCE* cmock_call_instance, can_t* can, can_msg_t* msg)
{
  cmock_call_instance->Expected_can = can;
  cmock_call_instance->Expected_msg = msg;
}

void can_send_msg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, can_t* can, can_msg_t* msg, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_can_send_msg_CALL_INSTANCE));
  CMOCK_can_send_msg_CALL_INSTANCE* cmock_call_instance = (CMOCK_can_send_msg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.can_send_msg_CallInstance = CMock_Guts_MemChain(Mock.can_send_msg_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_can_send_msg(cmock_call_instance, can, msg);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

